#!/bin/bash

Version="0.9.3";
AppData="$HOME/.KernUP";
AppName="kernup";
AliasName="$HOME/.bash_aliases";
InstalledVersion=$(uname -r | cut -d "-" -f1 | sort -V | cut -d "." -f1,2,3 | tail -n 1);
KernelInstalled=`echo $InstalledVersion | sed -e "s@.0@@g"`
Architecture=`uname -m`;
Core_Url="https://raw.githubusercontent.com/DamiaX/KernUP/master/KernUP";
Lang_Name="KernUP.lang";
Salt='';
Pass='';
term="/dev/tty";

Color()
{
Alert='33';
Text='36';
Wow='31';
Suprise='34';
Action='32';
}

Root()
{
if [ "$(id -u)" != "0" ]; then
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
if [ -z $Pass ] ; then
echo -e "\E[$Suprise;1m$AdminPass\033[0m"; 
read -s Password
Crypted=`echo $Password | openssl enc -aes-128-cbc -a -salt -pass pass:$Salt`
sed -i "s@^Pass='[a-zA-Z0-9_]*';@Pass='$Crypted';@g" $0
fi

Decrypted=`echo $Pass | openssl enc -aes-128-cbc -a -d -salt -pass pass:$Salt`
echo $Decrypted | sudo -S sh -c "bash $0 $1";
exit
fi
}

AutoRefresh()
{
for (( i=1; $i <= 2; )) ; do
Welcome;
GetLink;
sleep 3600;
done;
}

InstallApp()
{
if [ ! -f "$AppData/$AppName" ] ; then
echo -e -n "\E[$Alert;1m$Information\033[0m"; 
echo -e -n "\E[$Text;1m $AppInstallng\033[0m ";
echo -e "\E[$Alert;1m $Odplng\033[0m";
read Answer < $term;
Default_Answer "t";

if [[ $Answer == "T" || $Answer == "t" || $Answer == "y" || $Answer == "Y" ]]; then
cp -r $0 "$AppData/$AppName";
chmod +x -f "$AppData/$AppName";
echo "alias $AppName='$AppData/$AppName'" >> $AliasName;
crontab -l > "$AppData/Temp/cronfile";
echo "0 * * * * $AppData/$AppName -au" >> "$AppData/Temp/cronfile";
crontab "$AppData/Temp/cronfile";
rm -rf "$AppData/Temp/cronfile";
fi
fi
}

RemoveApp()
{
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e -n "\E[$Text;1m$AnswerRemove\033[0m ";
echo -e "\E[$Alert;1m $Odplng\033[0m";
read Answer;
Default_Answer "t";
if [[ $Answer == "T" || $Answer == "t" || $Answer == "y" || $Answer == "Y" ]]; then
sed -i "s@alias $AppName='$AppData/$AppName'@@g" $AliasName;
crontab -l > "$AppData/Temp/cronfile";
sed -i "s#0 * * * * $AppData/$AppName -au##g" "$AppData/Temp/cronfile";
crontab "$AppData/Temp/cronfile";
rm -rf $AppData;
fi
}

TestNetwork()
{
wget -q --spider http://google.com

if [ $? != 0 ]; then
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e "\E[$Wow;1m$Internetlng\033[0m";
exit;
fi
}

function Default_Answer()
{
if [ -z $Answer ]; then
Answer="$1";
fi
}

Language()
{
case $LANG in
*PL*) 
if [ ! -f "$AppData/$Lang_Name" ] ; then
Lang_pl=$(wget "https://raw.githubusercontent.com/DamiaX/KernUP/master/KernUP.pl.lang" -q -O -);
PL=`echo $Lang_pl > "$AppData/$Lang_Name"`;
fi
 ;;
*) 
if [ ! -f "$AppData/$Lang_Name" ] ; then
Lang_en=$(wget "https://raw.githubusercontent.com/DamiaX/KernUP/master/KernUP.en.lang" -q -O -);
EN=`echo $Lang_en > "$AppData/$Lang_Name"`;
fi
 ;;
esac
source "$AppData/$Lang_Name";
}

CreateData()
{
mkdir -p $AppData;
mkdir -p "$AppData/Temp";
}

Check_Distro()
{
if [[ "$(lsb_release -si)" != "Ubuntu" && "$(lsb_release -si)" != "LinuxMint" && "$(lsb_release -si)" != "elementary OS" && "$(lsb_release -si)" != "Debian" && "$(lsb_release -si)" != "elementary"  ]] ; then
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e "\E[$Wow;1m$Dist\033[0m";
   exit;
fi
}

RefreshSystem()
{
Root -su;
sudo apt-get update -y -qq;
sudo apt-get upgrade -y -qq;	
}

function GenerateSalt()
{
if [ -z $Salt ] ; then
RandomSalt=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $1  | head -n 1);
sed -i "s@^Salt='[a-zA-Z0-9_]*';@Salt='$RandomSalt';@g" $0
fi
}

Welcome()
{
clear;
Color;
CreateData;
Language;
echo -e -n "\E[28;1m [[ KernUP: \040"; echo -e -n "\E[31;1m$Version [Beta rc1.0] \033[0m"; echo -e -n "\E[28;1m ]]  -\040" ; echo -e "\E[$Alert;1m$EGGlng \033[0m"; 
GenerateSalt 20;
TestNetwork;
InstallApp;
AppUpdate;
}

AppUpdate()
{
Server_Version=$(wget "https://raw.githubusercontent.com/DamiaX/KernUP/master/Version" -q -O -);
New_Version=$(echo $Server_Version | tr '.' ',' | sed -e 's@,@@g');
Actual_Version=$(echo $Version | tr '.' ',' | sed -e 's@,@@g');
if [ $Actual_Version != $New_Version ]
then
echo -e -n "\E[$Alert;1m$Information\033[0m"; 
echo -e "\E[$Wow;1m $Updatelng\033[0m";
wget $Core_Url -q -O "$AppData/$AppName" | chmod +x -f "$AppData/$AppName";
echo -e -n "\E[$Alert;1m$Information\033[0m"; 
echo -e "\E[$Action;1m $Rebotlng \040";
bash "$AppData/$AppName";
exit;
fi
}

RemoveKernel()
{
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e -n "\E[$Suprise;1m$RemoveK_Ask \033[0m";
echo -e "\E[$Alert;1m$Odplng\033[0m";

read Answer < $term;
Default_Answer "t";

if [[ $Answer == "T" || $Answer == "t" || $Answer == "y" || $Answer == "Y" ]]; then
Root -rk;
apt-get remove -y --purge $(dpkg -l 'linux-image-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d');
apt-get remove -y --purge $(dpkg -l 'linux-headers-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d');
apt-get -y autoremove;
apt-get -y autoclean;
apt-get -y clean;
update-grub;	
fi
}

GetLink()
{
Kernel_List_Get=$(wget "http://kernel.ubuntu.com/~kernel-ppa/mainline" -q -O -); 
Kernel_Latest_Version=$(echo $Kernel_List_Get | sed -e 's@<a href="@ http://KernUP/@g' | sed -e 's@/">@ @g' | 
sed -e 's@[[:space:]]@\n@g' | sed -e '/^[ \t]*$/ d'  | grep 'http://KernUP/v' | sed -e "s@http://KernUP/@@g" | grep -v rc | sed -e "s@v@@g" |
awk 'function maxelt(vec,   i, ret) {
for (i in vec) 
{
if (ret == "" || vec[i] > ret)
               ret = vec[i]
     }
     return ret
}

{
     for(i = 1; i <= NF; i++)
          nums[NR, i] = $i
}

END {
     print maxelt(nums)
}'
);

Latest_Kernel_List=$(wget "http://kernel.ubuntu.com/~kernel-ppa/mainline/v$Kernel_Latest_Version" -q -O - );
Kernel_Link=$(echo $Latest_Kernel_List | sed -e's@~~~@@g' | sed -e "s@^@http://kernel.ubuntu.com/~kernel-ppa/mainline/$Latest_Kernel/@g" | sed -e 's@<a href="linux@ <arch>http://kernel.ubuntu.com/~kernel-ppa/mainline/v@g' | sed -e "s@<arch>http://kernel.ubuntu.com/~kernel-ppa/mainline/v@ \n <arch>http://kernel.ubuntu.com/~kernel-ppa/mainline/v$Kernel_Latest_Version/linux@g" | sed -e '0,/\(^\<arch>\)/s//\n\1/');
Kernel_Link_Architecture=$(echo $Kernel_Link | sed -e "s@_amd64.deb@</arch> @g" | sed -e "s@_i386.deb@</arch> @g" | sed -e "s@_all.deb@_all.deb</arch> @g" | awk -vRS="</arch>" '{gsub(/.*<arch.*>/,"");print}' | grep "http://" | tr ' ' '\n');
Headers_Download_Url_Generic=$(echo $Kernel_Link_Architecture | tr ' ' '\n' | grep "headers" | grep "generic" | sed -n -e '1p');
Image_Download_Url_Generic=$(echo $Kernel_Link_Architecture | tr ' ' '\n' | grep "image" | grep "generic" | sed -n -e '1p');
Headers_Download_Url_Lowlatency=$(echo $Kernel_Link_Architecture | tr ' ' '\n' | grep "headers" | grep "lowlatency" | sed -n -e '1p');
Image_Download_Url_Lowlatency=$(echo $Kernel_Link_Architecture | tr ' ' '\n' | grep "image" | grep "lowlatency" | sed -n -e '1p');
Kernel_Download_Url_All=$(echo $Kernel_Link_Architecture | tr ' ' '\n' | grep "all" | sed -n -e '1p');
DownloadKernel;
}

InstallKernel()
{
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e -n "\E[$Suprise;1m$InstallKernelAsk \033[0m";
echo -e "\E[$Alert;1m$Odplng\033[0m";
if [[ $1 != "1" ]] ; then
read Answer < $term;
Default_Answer "t";

if [[ $Answer == "T" || $Answer == "t" || $Answer == "y" || $Answer == "Y" ]]; then
Root -ik;
sudo dpkg -i *.deb;
fi

else
sudo dpkg -i *.deb;
fi

if [ $? == 0 ] ; then
echo -e -n "\E[$Alert;1m$Information\033[0m"; 
echo -e "\E[$Action;1m $Successlng \040"; 

else
echo -e -n "\E[$Alert;1m$Information\033[0m"; 
echo -e "\E[$Wow;1m $Abortlng\033[0m"; 
fi

cd $HOME;
rm -rf "$AppData/Temp";
}

DownloadKernel()
{
if [ $KernelInstalled == $Kernel_Latest_Version ] ; then
echo -e -n "\E[$Alert;1m$Information\033[0m"; 
echo -e "\E[$Action;1m $Gitlng \040"; 
else 
notify-send -u critical "KernUP" "$Chicklng"
echo -e -n "\E[$Alert;1m$Information \033[0m";
echo -e "\E[$Wow;1m$Chicklng \033[0m" ;
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e -n "\E[$Text;1m$Momlng \0$Alert[0m"; 
echo -e -n "\E[$Suprise;1m$Kernel_Installed \033[0m"; 
echo -e -n "\E[$Text;1m,$Givelng \0$Alert[0m"; 
echo -e -n "\E[$Suprise;1m$Kernel_Latest_Version\033[0m";
echo -e "\E[$Suprise;1m! \033[0m";
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e "\E[$Text;1m$Downloadlng \040"; 

cd "$AppData/Temp";
 
if  [ $Architecture == "x86_64" ] ; then
wget -q -c "$Headers_Download_Url_Generic"'_amd64.deb';
wget -q -c "$Image_Download_Url_Generic"'_amd64.deb';
wget -q -c "$Kernel_Download_Url_All";
fi

if [ $Architecture == "i686" ] || [ $Architecture == "i386" ] || [ $Architecture == "x86" ] ; then
wget -q -c "$Headers_Download_Url_Generic"'_i386.deb';
wget -q -c "$Image_Download_Url_Generic"'_i386.deb';
wget -q -c "$Kernel_Download_Url_All";
fi;

echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e "\E[$Text;1m $FinishDownload\040"; 
InstallKernel;
fi;
}

while [ "$1" ] ; do 
Welcome;
case "$1" in
  "--help"|"-h")
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e "\E[$Action;1m-u, --uninstall: $DeleteText $AppName \033[0m"; 
echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e "\E[$Action;1m-rk, --removekernel:  $RemoveText\033[0m"; 

exit;;

"--uninstall"|"-u") 
RemoveApp;
exit;;

"--removekernel"|"-rk") 
RemoveKernel;
exit;;

"--autorun"|"-au")
AutoRefresh;
exit;;

"--installkernel"|"-ik")
InstallKernel 1;
exit;;

"--systemupdate"|"-su")
RefreshSystem
exit;;
*)    
  echo -e -n "\E[$Alert;1m$Information \033[0m"; 
  echo -e "\E[$Wow;1m$UnknowOption '$1'\033[0m";  
  echo -e -n "\E[$Alert;1m$Information \033[0m";    
  echo -e "\E[$Action;1m$RunText '$AppName --help ' $InformationText\033[0m";             

      exit;
      ;;
    esac
done

Welcome;
GetLink;

echo -e -n "\E[$Alert;1m$Information \033[0m"; 
echo -e -n "\E[$Alert;1mAutor:\033[0m ";  echo -e -n "\E[$Suprise;1m Damian Majchrzak (DamiaX)\033[0m"; echo -e "\E[$Text;1m 2016\033[0m";
