#!/bin/bash

AppName="kernup";
Core_Url="https://raw.githubusercontent.com/DamiaX/KernUP/master/KernUP";
MD5_Url="https://raw.githubusercontent.com/DamiaX/KernUP/master/kernup.md5";

CheckSum()
{
md5sum -c "kernup.md5";

if [ $? == 0 ] ; then
rm -rf $AppName;
rm -rf "$Lang_Name";
rm -rf "kernup.md5";
mv "$AppName-new" "$AppName";
rm -rf $0;
bash "$AppName";
exit;
else
rm -rf "kernup.md5";
rm -rf "$AppName-new";
rm -rf $0;
exit
fi
}

Download()
{
wget $Core_Url -q -O "$AppName-new";
chmod +x "$AppName-new";
wget $MD5_Url -q -O "kernup.md5";
}

rm -rf "kernup.md5";
killall -q $AppName;

Download;
CheckSum;
